Rem Copyright (c) 2014, 2016, Oracle and/or its affiliates.  All rights reserved.
ALTER TABLE "SSB"."LINEORDER" INMEMORY MEMCOMPRESS FOR QUERY LOW;
ALTER TABLE "SSB"."PART" INMEMORY MEMCOMPRESS FOR QUERY LOW;
ALTER TABLE "SSB"."DATE_DIM" INMEMORY MEMCOMPRESS FOR QUERY LOW;
ALTER TABLE "SSB"."SUPPLIER" INMEMORY MEMCOMPRESS FOR QUERY LOW;
