sqlplus -S /nolog <<'EOF'

@../userlogin.sql

EXEC DBMS_INMEMORY.POPULATE('SSB', 'LINEORDER');
EXEC DBMS_INMEMORY.POPULATE('SSB', 'CUSTOMER');
EXEC DBMS_INMEMORY.POPULATE('SSB', 'DATE_DIM');
EXEC DBMS_INMEMORY.POPULATE('SSB', 'PART');
EXEC DBMS_INMEMORY.POPULATE('SSB', 'SUPPLIER');

EOF
