CREATE TABLE t1 (x, y)
PARTITION BY RANGE (x)
(
    PARTITION p1 VALUES LESS THAN (2500),
    PARTITION p2 VALUES LESS THAN (5000),
    PARTITION p3 VALUES LESS THAN (7500),
    PARTITION p4 VALUES LESS THAN (10000)
)
AS SELECT ROWNUM, ROWNUM FROM dual CONNECT BY LEVEL < 10000;

CREATE TABLE t2 (x, y)
PARTITION BY RANGE (x)
(
    PARTITION p1 VALUES LESS THAN (5000),
    PARTITION p2 VALUES LESS THAN (10000),
    PARTITION p3 VALUES LESS THAN (15000),
    PARTITION p4 VALUES LESS THAN (20000)
)
AS SELECT ROWNUM, ROWNUM FROM dual CONNECT BY LEVEL < 20000;

SELECT count(*) FROM t1, t2 WHERE t1.x = t2.x;

@../showplan

DROP TABLE t1;
DROP TABLE t2;

EXIT
