SET TIMING OFF
SET LINES 120
SET ECHO ON

DROP TABLE iot_ingest PURGE;

CREATE TABLE iot_ingest (
    id     NUMBER PRIMARY KEY,
    value  CHAR(8)
);

SET TIMING ON
BEGIN
    FOR i IN 1..1000000 LOOP
        INSERT INTO iot_ingest VALUES (
            i,
            'ABCDEFGH'
        );

        COMMIT;
    END LOOP;

    COMMIT;
END;
/
SET TIMING OFF

DROP TABLE iot_ingest PURGE;

CREATE TABLE iot_ingest (
    id     NUMBER PRIMARY KEY,
    value  CHAR(8)
);

SET TIMING ON
BEGIN
    FOR i IN 1..1000000 LOOP
        INSERT INTO iot_ingest VALUES (
            i,
            'ABCDEFGH'
        );

        IF MOD(i, 5000) = 0 THEN
            COMMIT;
        END IF;
    END LOOP;

    COMMIT;
END;
/
SET TIMING OFF

DROP TABLE iot_ingest PURGE;

CREATE TABLE iot_ingest (
    id     NUMBER PRIMARY KEY,
    value  CHAR(8)
)
SEGMENT CREATION IMMEDIATE
MEMOPTIMIZE FOR WRITE;

SET TIMING ON
BEGIN
    FOR i IN 1..1000000 LOOP
        INSERT /*+ MEMOPTIMIZE_WRITE */ INTO iot_ingest VALUES (
            i,
            'ABCDEFGH'
        );

    END LOOP;

END;
/
SET TIMING OFF

SET NUMFORMAT 999,999,999,999
SELECT * FROM V$MEMOPTIMIZE_WRITE_AREA;
SELECT DBMS_MEMOPTIMIZE.GET_APPLY_HWM_SEQID FROM dual;
SELECT DBMS_MEMOPTIMIZE.GET_WRITE_HWM_SEQID FROM dual;

EXEC dbms_memoptimize_admin.writes_flush;

SELECT * FROM V$MEMOPTIMIZE_WRITE_AREA;
SELECT DBMS_MEMOPTIMIZE.GET_APPLY_HWM_SEQID FROM dual;
SELECT DBMS_MEMOPTIMIZE.GET_WRITE_HWM_SEQID FROM dual;

EXEC DBMS_MEMOPTIMIZE.WRITE_END;
SELECT DBMS_MEMOPTIMIZE.GET_APPLY_HWM_SEQID FROM dual;
SELECT DBMS_MEMOPTIMIZE.GET_WRITE_HWM_SEQID FROM dual;
